name: "Report Issue"
description: "Report broken links or missing materials."
body:
  - type: input
    id: file
    attributes:
      label: "File / Folder Name"
  - type: textarea
    id: details
    attributes:
      label: "Describe the problem"
